---
- name: Provision local laptop (simple)
  hosts: localhost
  become: true
  gather_facts: true
  vars_files:
    - vars.yml

  tasks:
    - name: Add Brave keyring when brave-browser requested
      get_url:
        url: https://brave-browser-apt-release.s3.brave.com/brave-browser-archive-keyring.gpg
        dest: /usr/share/keyrings/brave-browser-archive-keyring.gpg
        mode: "0644"
      when: "'brave-browser' in common_packages"
      tags: [packages]

    - name: Add Brave apt repository when brave-browser requested
      apt_repository:
        repo: "deb [signed-by=/usr/share/keyrings/brave-browser-archive-keyring.gpg arch=amd64] https://brave-browser-apt-release.s3.brave.com/ stable main"
        filename: brave-browser-release
        state: present
        update_cache: true
      when: "'brave-browser' in common_packages"
      tags: [packages]

    - name: Install packages (apt)
      apt:
        name: "{{ common_packages }}"
        state: present
        update_cache: true
      when: common_packages | length > 0
      tags: [packages]

    - name: Ensure SSH service enabled and started (if openssh-server requested)
      service:
        name: ssh
        enabled: true
        state: started
      when: "'openssh-server' in common_packages"
      tags: [packages]

    # Xsession desktop entry for GDM to run ~/.xsession
    - name: Ensure xsessions directory exists
      file:
        path: /usr/share/xsessions
        state: directory
        mode: "0755"
      tags: [xsession]

    - name: Install Xsession desktop entry for GDM
      copy:
        dest: /usr/share/xsessions/xsession.desktop
        mode: "0644"
        content: |
          [Desktop Entry]
          Name=Xsession
          Comment=Run the system Xsession which sources ~/.xsession
          Exec=/etc/X11/Xsession
          TryExec=/etc/X11/Xsession
          Type=Application
          DesktopNames=X-Generic
      tags: [xsession]

    - name: Symlink ~/.xsession from dotfiles (if present)
      file:
        src: "{{ ansible_env.HOME }}/git/cwage/dotfiles/.xsession"
        dest: "{{ ansible_env.HOME }}/.xsession"
        state: link
        force: true
      when: lookup('ansible.builtin.fileglob', ansible_env.HOME + '/git/cwage/dotfiles/.xsession', wantlist=False) != ''
      tags: [xsession]
